---
version: '3'
services:


  web:
    build: tomcat/
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - share:/opt/tomcat/webapps/

volumes:
  share:
