---
version: '3'
services:

  backend:
    build: maven/
    container_name: maven
    volumes:
      - hw12_share:/opt/javaapp/target/

  web:
    build: tomcat/
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - hw12_share:/opt/tomcat/webapps/

volumes:
  hw12_share:
