---
version: '3'
services:
  db:
    container_name: db
    image: mysql:5.5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1qazxsw2
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1qazxsw2

    volumes:
      - ./dbdata:/var/lib/mysql/

  web:
    build: tomcat/
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      DB_USERNAME: user
      DB_PASSWORD: 1qazxsw2
      DB_IP: db
      DB_NAME: mydb
    volumes:
      - hw12_share:/opt/tomcat/webapps/
      - hw12_ROOT:/opt/tomcat/ROOT/

  backend:
    build: maven/
    container_name: maven
    volumes:
      - hw12_share:/opt/javaapp/target/
      - hw12_ROOT:/opt/javaapp/WebContent/
volumes:
  hw12_share:
  hw12_ROOT:
  dbdata:
