---
version: '3'
services:
  backend:
    build: maven/
    container_name: maven
    volumes:
      - share:/opt/javaapp/target/

  web:
    build: tomcat/
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - share:/opt/tomcat/webapps/

  mysql_db:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1qazxsw2
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1qazxsw2
    volumes:
      - ./dbdata:/var/lib/mysql/

volumes:
  share:
